specVersion: 0.2.0
name: parallel-subql-starter
version: 0.0.4
description: This project can be use as a starting point for Parallel network.
repository: https://github.com/subquery/parallel-subql-starter
schema:
  file: ./schema.graphql
network:
  endpoint: wss://parallel.api.onfinality.io/public-ws
  genesisHash: '0xe61a41c53f5dcd0beb09df93b34402aada44cb05117b71059cce40a2723a4e97'
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Deposit
        - handler: handleCall
          kind: substrate/CallHandler
