specVersion: 0.2.0
name: karura-subql-starter
version: 0.0.4
description: This project can be use as a starting point for Karura network.
repository: https://github.com/subquery/karura-subql-starter
schema:
  file: ./schema.graphql
network:
  endpoint: wss://karura.api.onfinality.io/public-ws
  genesisHash: '0xbaf5aabe40646d11f0ee8abbdc64f4a4b7674925cba08e4a05ff9ebed6e2126b'
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Deposit
        - handler: handleCall
          kind: substrate/CallHandler
