specVersion: 0.2.0
name: altair-subql-starter
version: 0.0.4
description: This project can be use as a starting point for Altair network.
repository: https://github.com/subquery/altair-subql-starter
schema:
  file: ./schema.graphql
network:
  endpoint: wss://altair.api.onfinality.io/public-ws
  genesisHash: '0xaa3876c1dc8a1afcc2e9a685a49ff7704cfd36ad8c90bf2702b9d1b00cc40011'
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Deposit
        - handler: handleCall
          kind: substrate/CallHandler
