specVersion: 0.2.0
name: statemint-subql-starter
version: 0.0.4
description: This project can be use as a starting point for Statemint network.
repository: https://github.com/subquery/statemint-subql-starter
schema:
  file: ./schema.graphql
network:
  endpoint: wss://statemint.api.onfinality.io/public-ws
  genesisHash: '0x68d56f15f85d3136970ec16946040bc1752654e906147f7e43e9d539d7c3de2f'
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Deposit
        - handler: handleCall
          kind: substrate/CallHandler
