specVersion: 0.2.0
name: kusama-subql-starter
version: 0.0.4
description: This project can be use as a starting po...
repository: https://github.com/subquery/kusama-subql-starters
schema:
  file: ./schema.graphql
network:
  endpoint: wss://kusama.api.onfinality.io/public-ws
  genesisHash: '0xb0a8d493285c2df73290dfb7e61f870f17b41801197a149ca93654499ea3dafe'
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Deposit
        - handler: handleCall
          kind: substrate/CallHandler
