specVersion: 0.2.0
name: clover-subql-starter
version: 0.0.4
description: This project can be use as a starting po...
repository: https://github.com/subquery/clover-subql-starters
schema:
  file: ./schema.graphql
network:
  endpoint: wss://clover.api.onfinality.io/public-ws
  genesisHash: '0x5c7bd13edf349b33eb175ffae85210299e324d852916336027391536e686f267'
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Deposit
        - handler: handleCall
          kind: substrate/CallHandler
