specVersion: 0.2.0
name: automata-subql-starter
version: 0.0.4
description: This project can be use as a starting point for Automata network.
repository: https://github.com/subquery/automata-subql-starter
schema:
  file: ./schema.graphql
network:
  endpoint: wss://automata.api.onfinality.io/public-ws
  genesisHash: '0xc8eda34601b5a48c73f47ee39a3a86a858c34f044185b17dc7d5ad155813dc63'
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Deposit
        - handler: handleCall
          kind: substrate/CallHandler
