specVersion: 0.2.0
name: nodle-subql-starter
version: 0.0.4
description: This project can be use as a starting point for nodle network.
repository: https://github.com/subquery/nodle-subql-starter
schema:
  file: ./schema.graphql
network:
  endpoint: wss://nodle.api.onfinality.io/public-ws
  genesisHash: '0xa3d114c2b8d0627c1aa9b134eafcf7d05ca561fdc19fb388bb9457f81809fb23'
  chaintypes:
    file: ./dist/chaintypes.js
  dictionary: https://api.subquery.network/sq/subquery/nodle-dictionary
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Deposit
        - handler: handleCall
          kind: substrate/CallHandler
