specVersion: 0.2.0
name: contextfree-subql-starter
version: 0.0.4
description: This project can be use as a starting point for ContextFree network.
repository: https://github.com/subquery/contextfree-subql-starter
schema:
  file: ./schema.graphql
network:
  endpoint: wss://contextfree.api.onfinality.io/public-ws
  genesisHash: '0x6254c948b5eb7199a112cb308be3385c39c8c942625540ac749c77fe2aebc299'
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Deposit
        - handler: handleCall
          kind: substrate/CallHandler
